export const TYPES = {
    LOGIN_AUTH: "LOGIN_AUTH",
    CREATE_DATA: "CREATE_DATA",
    DELETE_DATA: "DELETE_DATA",
    GET_DATA: "GET_DATA",
    DELETE_SCHEDULE: "DELETE_SCHEDULE",
    DELETE_ALL_DATA: "DELETE_ALL_DATA",
    SEARCH_DATA: "SEARCH_DATA"  
}